### ISSUE TITLE
Assert in getLocalSupportPointWithoutMargin

### ISSUE THREAD

**Issue by Paril** [DanielChappuis/reactphysics3d#91] opened 2019-05-18 05:15 UTC
I have a simple convex object added to a concave mesh world. For some reason, every collision continuously reports this assert:

    assert(maxDotProduct >= decimal(0.0));

What does the assert mean, and what do I do to resolve it? I have ensured that all of my objects are counter-clockwise-facing (I checked via exporting the resulting meshes to .obj).

**Comment by DanielChappuis** [comment] 2019-05-18 12:31
What kind of mesh are you using ? Do you also have a stack trace with the assert ?

**Comment by StephenNneji** [comment] 2019-07-12 09:52
Hi, 
I get the same error with a convex mesh 
The stack trace is :
`testbed.exe!reactphysics3d::ConvexMeshShape::getLocalSupportPointWithoutMargin(const reactphysics3d::Vector3 & direction) Line 76	C++
testbed.exe!reactphysics3d::GJKAlgorithm::testCollision(reactphysics3d::NarrowPhaseInfo * narrowPhaseInfo, bool reportContacts) Line 109	C++	testbed.exe!reactphysics3d::SphereVsConvexPolyhedronAlgorithm::testCollision(reactphysics3d::NarrowPhaseInfo * narrowPhaseInfo, bool reportContacts, reactphysics3d::MemoryAllocator & memoryAllocator) Line 58	C++
testbed.exe!reactphysics3d::CollisionDetection::testOverlap(reactphysics3d::CollisionBody * body, reactphysics3d::OverlapCallback * overlapCallback, unsigned short categoryMaskBits) Line 711	C++
testbed.exe!reactphysics3d::CollisionWorld::testOverlap(reactphysics3d::CollisionBody * body, reactphysics3d::OverlapCallback * overlapCallback, unsigned short categoryMaskBits) Line 256	C++
testbed.exe!enginxscene::EnginxScene::update() Line 142	C++
testbed.exe!TestbedApplication::update() Line 218	C++
testbed.exe!TestbedApplication::drawContents() Line 225	C++
nanogui.dll!nanogui::Screen::drawAll() Line 390	C++
nanogui.dll!nanogui::mainloop(int refresh) Line 99	C++
testbed.exe!main(int argc, char * * argv) Line 43	C++
[External Code]	`

**Comment by DanielChappuis** [comment] 2019-07-12 13:59
Hello,

Thanks for reporting this.

It seems that you are using the testbed application of ReactPhysics3D. Can you share the code that you changed in the testbed (if any) and also your convex mesh (obj file) so that I can try to reproduce the issue on my side within the testbed application ?

**Comment by StephenNneji** [comment] 2019-07-12 14:36
The changed files and mesh can be downloaded here [https://www.dropbox.com/s/q17tq1hga2rogtj/files.zip?dl=0](url)

The crash occurs when the sphere object collides with the convex mesh.

**Comment by DanielChappuis** [comment] 2019-07-16 18:48
Thanks a lot for the code and mesh file. I was able to reproduce the issue and I think I know what the problem is. 

Currently, it is required that the origin of a convex mesh is inside the convex mesh itself. It seems that with your mesh, the (0, 0, 0) coordinate is outside the convex mesh which is not currently supported by the ReactPhysics3D library.

I will update the user manual to make this more clear.

**Comment by DanielChappuis** [comment] 2019-08-26 16:17
Can I close this issue ?

**Comment by StephenNneji** [comment] 2019-08-26 18:50
Yes, Thanks for the quick response

**Comment by DanielChappuis** [comment] 2019-08-26 18:54
You are welcome !

**Closed by DanielChappuis** 2019-08-26 18:54 UTC
