### ISSUE TITLE
Assertion fails when destroying rigid body

### ISSUE THREAD

**Issue by afpatmin** [DanielChappuis/reactphysics3d#45] opened 2018-05-14 19:07 UTC
Assertion mNbNonUsedMovedShapes <= mNbMovedShapes (in function BroadphaseAlgorithm::removeMovedCollisionShape) fails seemingly at random upon destroying rigid bodies.

Edit: I don't know if this helps but if I create 3 rigid bodies and destroy them each before creating the next one, the assertion always fails when the third rigid body is destroyed.

**Comment by DanielChappuis** [comment] 2018-05-15 10:01
Hello. Thanks a lot for reporting this.

If I understand correctly, you do the following:

- Create body 1
- Destroy body 1
- Create body 2
- Destroy body 2
- Create body 3
- Destroy body 3
-  Crash here !

Are you doing this before updating the world (calling the update() method on your world) or between several calls to the update() method ?

**Comment by DanielChappuis** [comment] 2018-05-15 10:05
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Bug #45 - Assert when destroying bodies](https://trello.com/c/9P2GuJFy/6-fix-bug-45-assert-when-destroying-bodies)

**Comment by afpatmin** [comment] 2018-05-15 10:27
Yes exactly in the order you specified, I make multiple calls to world.update() in between. What I do is I create a new body every 2-4 seconds and destroy them each second after creating them.

Also the bodies all share the same ColissionShape, which is allocated in a separate pool and using unique_ptr

**Comment by Hemmy123** [comment] 2018-05-15 11:57
Hi, I've also been having the same issue. I'm creating 80+ rigid bodies for a level in a game, destroying them all when a new level is loaded, and then created a new set of rigid bodies. The error seems to occur randomly when destroying the them.

**Comment by DanielChappuis** [comment] 2018-05-16 06:36
Ok thanks a lot. I will check into that.

**Comment by DanielChappuis** [comment] 2018-05-23 10:44
I have pushed a modification in the master branch to fix this issue.
Can I ask you to check if the issue is now fixed on your side ?

**Comment by afpatmin** [comment] 2018-05-24 20:05
That fixed it on my end

**Comment by DanielChappuis** [comment] 2018-05-25 07:03
Great

**Closed by DanielChappuis** 2018-05-25 07:03 UTC
Labels: bug
