### ISSUE TITLE
Opening ReactPhysics3D built for Visual Studio 2013 produces make_pair errors.

### ISSUE THREAD

**Issue by sydan92** [DanielChappuis/reactphysics3d#4] opened 2015-04-02 10:49 UTC
After building ReactPhysics3D with CMake for Visual Studio I get an intellisense error coming from the ConvexMeshShape.h file:

	1	IntelliSense: no instance of function template "std::make_pair" matches the argument list argument types are: (reactphysics3d::uint, std::set<reactphysics3d::uint, std::less<reactphysics3d::uint>, std::allocator<char32_t>>)	c:\LocalProjects\CollisionDetection\reactphysics\reactphysics3d-0.5.0\reactphysics3d\src\collision\shapes\ConvexMeshShape.h	227	36	reactphysics3d

**Comment by sydan92** [comment] 2015-04-02 11:03
Some additional information that might help with this issue, I decided to go ahead and try and include the reactphysics3D.h in my project anyway to see what would happen, after adding the additional dependency and trying to build I get: 

     Error	1	error C2664: 'std::make_pair' : cannot convert parameter 1 from 'reactphysics3d::uint' to 'reactphysics3d::uint &&'	c:\localprojects\collisiondetection\reactphysics\reactphysics3d-0.5.0\reactphysics3d\src\collision\shapes\convexmeshshape.h	227	ReactPhysics3DApp

(twice, line 227 and 232)

Which matches up with the intellisense error.

**Comment by DanielChappuis** [comment] 2015-04-10 06:40
Thanks a lot for reporting this issue.

The issue has been fixed in this commit: 3aaac820e0d184959033b98b26b7811ac86935bb
You can simply pull again the "master" branch to get the update.

Please, let me know if the issue is now fixed on your side.

**Closed** 2015-04-14 05:57 UTC
Labels: bug
