### ISSUE TITLE
Joint Issues

### ISSUE THREAD

**Issue by maluoi** [DanielChappuis/reactphysics3d#102] opened 2019-08-19 19:10 UTC
I've been attempting to create a button pressable by physics! I have a slider joint that has limits for how far it'll slide, and a constant motor to force it back up after its been pressed down.

This is what it looks like when it's mostly behaving: https://twitter.com/koujaku/status/1163331565994164225

Unfortunately, there's all sorts of strange behavior when I interact with the button! Occasionally it'll behave as expected, but most of the time it'll cycle up and down on its own, get stuck down, get stuck up, and various other weirdness. This'll happen with the hands, and also when dropping regular objects on the buttons.

Any tips on getting this to work? Or is this a bug?

**Comment by DanielChappuis** [comment] 2019-08-20 05:49
Thanks a lot for your feedback.

I don't think it's a known issue. Are you able to provide some code for a basic setup of a simple SliderJoint and motor that is not behaving correctly ? This would really help me to reproduce the issue on my side.

**Comment by maluoi** [comment] 2019-08-20 06:51
I'll give you some info right away, and I'll try and find some time later to put together some nicer repro code! I've frameworkified my code a bit, so it'll be a bit of work to translate it back to ReactPhysics code :) I've also tried variants on this setup, all the ones I tried were misbehaving. Here's my current setup!

The joint info:

```
const Vector3 anchorPoint = rp3d::decimal(0.5) * (a->getTransform().getPosition() + b->getTransform().getPosition()); 
const Vector3 axis = (b->getTransform().getPosition() - a->getTransform().getPosition() ); 

SliderJointInfo jointInfo(a, b, anchorPoint, axis);
jointInfo.isLimitEnabled = true;
jointInfo.minTranslationLimit = -axis.length()/2;
jointInfo.maxTranslationLimit = 0.001f;

jointInfo.isMotorEnabled = true;
jointInfo.motorSpeed     = axis.length() * 20;
jointInfo.maxMotorForce  = 100;
jointInfo.isCollisionEnabled = true;
```

The two rigidbodies are about 2cm away from eachother, all data set before adding the joint!
Rigidbody a:
BodyType::STATIC
No collision shape

Rigidbody b:
BodyType::DYNAMIC
BoxShape collider, 40kg, 10x10x4cm (0.1x0.1x0.04)
Gravity false

**Comment by DanielChappuis** [comment] 2020-05-15 21:53
Hello,

I have recently fixed a bug with limits in the SliderJoint and HingeJoint with this [commit](https://github.com/DanielChappuis/reactphysics3d/commit/c1f40ac45618fbeceddbbe0ab909457e076bd7f1) in the master branch.

Maybe it also fixes the issue you have reported. Are you able to try it again with this fix ?

**Comment by DanielChappuis** [comment] 2021-02-09 22:34
I am closing this issue. Do not hesitate to reopen it if you think the issue is not resolved.

**Closed by DanielChappuis** 2021-02-09 22:34 UTC
