### ISSUE TITLE
EventListener seems to miss collisions

### ISSUE THREAD

**Issue by Hemmy123** [DanielChappuis/reactphysics3d#46] opened 2018-05-15 12:39 UTC
I'm trying to detect collisions between certain objects using a class that extends `EventListener`. I pass an ID of an object into the `mUserData` variable when creating a `ProxyShape`. 

Each frame, the listener saves the ID of the two objects colliding in the `newContact` method. These two IDs are then checked outside to see if they match (if the player has collided with an enemy for example).

The code seems to work sometimes in Debug mode (collisions between certain objects are not always picked up), and doesn't work at all in Release. 

Apologies if I'm using the library wrong as I'm still rather new to using physics engines.

Thanks

**Comment by DanielChappuis** [comment] 2018-05-16 06:39
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Bug #46 - EventListener miss collisions](https://trello.com/c/Ab27kQO6/7-fix-bug-46-eventlistener-miss-collisions)

**Comment by DanielChappuis** [comment] 2018-05-23 10:45
Thanks a lot for reporting this. 

I have not been able to reproduce this issue on my side.

Note that when you create new bodies after some bodies have been destroyed, the new bodies can have the same Ids as the bodies that have previously been destroyed.

Are you able to produce a small piece of code with an EventListener that is not working correctly so that I can test it ?

**Comment by DanielChappuis** [comment] 2020-06-02 08:44
The version v0.8.0 of ReactPhysics3D has been released. In this version, the way to report contacts with EventListener has changed. Take a look at the user manual [here ](https://reactphysics3d.com/usermanual.html#x1-8300015)for more information. This issue might have been fixed in this version because of the refactoring.

I am closing this issue now but do not hesitate to reopen it if you still having this issue with the new version.

**Closed by DanielChappuis** 2020-06-02 08:44 UTC
