### ISSUE TITLE
Assertion Fails and Segmentation Faults With Concave Shape

### ISSUE THREAD

**Issue by KarateKidzz** [DanielChappuis/reactphysics3d#192] opened 2021-02-10 09:44 UTC
Hi, I started using this library yesterday to help with my undergrad dissertation. I've been enjoying the library but getting tons of segmentation faults. I'm on macOS 10.15.7 using XCode.
```
tid_307 (1): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```
This was very prevalent with my first implementation of the physics code. I need to test whether bunch of voxels collide with a mesh, so was creating a box shape and collider body for each voxel. This code produced tons of segmentation faults.

I've since changed the code to use one box shape and collider, and purely move the transform to each voxel. However, with this change I now get an assertion fail:
```
assert(contactPoints[i].size() == 0);
````
This assertion only triggers on the 5th/6th voxel, however, which makes the problem even stranger. However, I assume it just happens that the 5th/6th voxel is actually colliding so there's a difference in the methods. Ie, for the first few voxels, there's no collision so no contact points. But for the 5th or 6th, it's colliding so there are collision points.

And if I comment out the assertion, I get more segmentation faults from this code.
```
mCollidersComponents.mCollisionShapes[i]->computeAABB(aabb, transform * mCollidersComponents.mLocalToBodyTransforms[i]);
```

To note about the segmentation faults, they've happened in multiple places and it doesn't seem to be one problematic line of code. However, there seems to be a similarity in that it's related to the entity component system / pointers to entities.

**Segmentation Fault Stack Trace**
```
#0	0x000000015184d383 in reactphysics3d::BroadPhaseSystem::updateCollidersComponents(unsigned int, unsigned int, float) at OpenPL/External/ReactPhysics3D/src/systems/BroadPhaseSystem.cpp:180
#1	0x000000015184d0fc in reactphysics3d::BroadPhaseSystem::updateCollider(reactphysics3d::Entity, float) at OpenPL/External/ReactPhysics3D/src/systems/BroadPhaseSystem.cpp:122
#2	0x00000001517b4894 in reactphysics3d::CollisionDetectionSystem::updateCollider(reactphysics3d::Entity, float) at OpenPL/External/ReactPhysics3D/include/reactphysics3d/systems/CollisionDetectionSystem.h:435
#3	0x00000001517b46de in reactphysics3d::CollisionBody::updateBroadPhaseState(float) const at OpenPL/External/ReactPhysics3D/src/body/CollisionBody.cpp:233
#4	0x00000001517b543d in reactphysics3d::CollisionBody::setTransform(reactphysics3d::Transform const&) at OpenPL/External/ReactPhysics3D/src/body/CollisionBody.cpp:398
#5	0x0000000151892065 in PL_SCENE::FillVoxels() at OpenPL/Source/Private/Objects/Private/PL_SCENE.cpp:415
#6	0x00000001518907b8 in PL_SCENE::Voxelise(PLVector, PLVector, float) at OpenPL/Source/Private/Objects/Private/PL_SCENE.cpp:308
#7	0x00000001519f7406 in ::PL_Scene_Voxelise(PL_SCENE *, PLVector *, PLVector *, float) at OpenPL/Source/Private/OpenPL.cpp:109
```

**Assertion Stack Trace**
```
#4	0x0000000156f21aa8 in reactphysics3d::NarrowPhaseInfoBatch::clear() at OpenPL/External/ReactPhysics3D/src/collision/narrowphase/NarrowPhaseInfoBatch.cpp:133
#5	0x0000000156f2033a in reactphysics3d::NarrowPhaseInfoBatch::~NarrowPhaseInfoBatch() at OpenPL/External/ReactPhysics3D/src/collision/narrowphase/NarrowPhaseInfoBatch.cpp:47
#6	0x0000000156f20545 in reactphysics3d::NarrowPhaseInfoBatch::~NarrowPhaseInfoBatch() at OpenPL/External/ReactPhysics3D/src/collision/narrowphase/NarrowPhaseInfoBatch.cpp:46
#7	0x0000000156f87416 in reactphysics3d::NarrowPhaseInput::~NarrowPhaseInput() at OpenPL/External/ReactPhysics3D/include/reactphysics3d/collision/narrowphase/NarrowPhaseInput.h:54
#8	0x0000000156f86a05 in reactphysics3d::NarrowPhaseInput::~NarrowPhaseInput() at OpenPL/External/ReactPhysics3D/include/reactphysics3d/collision/narrowphase/NarrowPhaseInput.h:54
#9	0x0000000156f9f7df in reactphysics3d::CollisionDetectionSystem::testOverlap(reactphysics3d::CollisionBody*, reactphysics3d::CollisionBody*) at OpenPL/External/ReactPhysics3D/src/systems/CollisionDetectionSystem.cpp:1478
#10	0x0000000156f803be in reactphysics3d::PhysicsWorld::testOverlap(reactphysics3d::CollisionBody*, reactphysics3d::CollisionBody*) at OpenPL/External/ReactPhysics3D/src/engine/PhysicsWorld.cpp:303
#11	0x0000000156fd9068 in PL_SCENE::FillVoxels() at OpenPL/Source/Private/Objects/Private/PL_SCENE.cpp:419
#12	0x0000000156fd7798 in PL_SCENE::Voxelise(PLVector, PLVector, float) at OpenPL/Source/Private/Objects/Private/PL_SCENE.cpp:308
#13	0x000000015713e3e6 in ::PL_Scene_Voxelise(PL_SCENE *, PLVector *, PLVector *, float) at OpenPL/Source/Private/OpenPL.cpp:109
```

**My Code**
The code is slightly stripped down but still contains the core logic.
```
// Create box collider at origin. Will get moved later
CollisionBody* VoxelBody = PhysicsWorld->createCollisionBody(Transform::identity());
BoxShape* VoxelShape = PhysicsSystem->createBoxShape(Vector3(VoxelHalfSize, VoxelHalfSize, VoxelHalfSize));
VoxelBody->addCollider(VoxelShape, Transform::identity());

std::unique_ptr<TriangleVertexArray> TriangleArray (new TriangleVertexArray(static_cast<unsigned int>(Mesh.Vertices.cols()),
                                                                     Mesh.Vertices.data(),
                                                                     3 * sizeof(double),
                                                                     static_cast<unsigned int>(Mesh.Indices.cols()),
                                                                     Mesh.Indices.data(),
                                                                     3 * sizeof(int),
                                                                     TriangleVertexArray::VertexDataType::VERTEX_DOUBLE_TYPE,
                                                                     TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE));
        
TriangleMesh* TriangleMesh = PhysicsSystem->createTriangleMesh();
TriangleMesh->addSubpart(TriangleArray.get());
        
ConcaveMeshShape* ConcaveMesh = PhysicsSystem->createConcaveMeshShape(TriangleMesh);
        
CollisionBody* MeshBody = PhysicsWorld->createCollisionBody(Transform::identity());
MeshBody->addCollider(ConcaveMesh, Transform::identity());

for (int i = 0; i < MeshCells->size(); i++)
{
    auto& Cell = (*MeshCells.get())[i];
            
    Eigen::Vector3d Pos = Cell->WorldPosition;
    Transform VoxelTransform = Transform::identity();
    VoxelTransform.setPosition(Vector3(Pos.x(), Pos.y(), Pos.z()));
    VoxelBody->setTransform(VoxelTransform);

    if (PhysicsWorld->testOverlap(MeshBody, VoxelBody))
    {
        Cell->Absorptivity = 0.75f; // DEBUG. TODO: Fill this with an actual value
    }
}
```

I've just done a little more testing and there are no problems if I use a box shape for the mesh body. It seems the concave mesh shape is the problem.

I understand concave mesh collision is expensive but I was hoping to have a "one size fits all" solution. As time isn't really a concern, I hoped a concave mesh could work for all meshes I throw at it.

You can view my roughly up to date code at: [https://github.com/KarateKidzz/OpenPL](https://github.com/KarateKidzz/OpenPL)

**Comment by KarateKidzz** [comment] 2021-02-10 10:32
Setting to 1 triangle (`new TriangleVertexArray(nbVerts = 3, nbTriangles = 1`) still results in the same assertion fail. However, the difference this time is it triggers at voxel 700.

I've also tried lengths `3,3` and `1,1`.

I also tried changing the winding order. This produces a different assertion when doing lengths `3,3`: `assert(contactNormal.lengthSquare() > decimal(0.8));` on line 76 of ContactPointInfo.h.

However, I'm assuming this is more to do with the incorrect number of vertices to indices. Am I correct in thinking a `nbTriangles` of 1 would result in the library finding 3 indices? Therefore checking across 9 different doubles?

The Mesh.Vertices and Mesh.Indices should definitely persist, afaik. And the triangle array gets destroyed after all the voxels have tested their overlaps with the mesh. After that, the mesh isn't needed. However, this is all destroyed inside a for each loop that loops through every mesh provided to OpenPL. Does the triangle array need to persist during the entire world?

**Comment by DanielChappuis** [comment] 2021-02-14 08:21
> The Mesh.Vertices and Mesh.Indices should definitely persist, afaik. And the triangle array gets destroyed after all the voxels have tested their overlaps with the mesh. After that, the mesh isn't needed. However, this is all destroyed inside a for each loop that loops through every mesh provided to OpenPL. Does the triangle array need to persist during the entire world?

If the asserts happen when you call testOverlap() and at this point the Mesh.Indices and Mesh.Vertices data is not destroyed yet therefore, this is not what is wrong.

> However, I'm assuming this is more to do with the incorrect number of vertices to indices. Am I correct in thinking a `nbTriangles` of 1 would result in the library finding 3 indices? Therefore checking across 9 different doubles?

I am not sure I really understand. Can you please post the code that you use to create your ConcaveMeshShape with a single triangle ? I still don't know what types and values you are using in Mesh.Indices.data() and Mesh.Vertices.data().

**Comment by KarateKidzz** [comment] 2021-02-15 09:16
[Here](https://github.com/KarateKidzz/OpenPL/blob/develop/OpenPL/Source/Private/Objects/Private/PL_SCENE.cpp) is the main file that handles geometry processing and physics.

The method *AddAndConvertGameMesh* on line 54 takes a mesh from Unity and converts it to Eigen data.

Then *FillVoxels* on line 311 does the physics calculations.

The geometry from Unity is sent over with this code:

```
List<Vector3> Verts = new List<Vector3>();
Meshes[i].mesh.GetVertices(Verts);
List<int> Inds = new List<int>();
Meshes[i].mesh.GetIndices(Inds, 0);

GCHandle VertHandle = GCHandle.Alloc(Verts.ToArray(), GCHandleType.Pinned);
GCHandle IndHandle = GCHandle.Alloc(Inds.ToArray(), GCHandleType.Pinned);

int Index = 5;            

try
{
    PLVector pos = Meshes[i].transform.position.ToPLVector();
    PLQuaternion rot = Meshes[i].transform.rotation.ToPLQuaternion();
    PLVector scal = Meshes[i].transform.lossyScale.ToPLVector();
    RESULT MeshResult = PL_Scene_AddMesh(Scene, ref pos, ref rot, ref scal, VertHandle.AddrOfPinnedObject(), Verts.Count, IndHandle.AddrOfPinnedObject(), Inds.Count, out Index);
}
finally
{
    VertHandle.Free();
    IndHandle.Free();
}
```

As for the `Mesh.Indices.data()` and such, as far as I know, it returns the raw array that Eigen stores its matrices and vectors as. I'm also storing all of the data as column-major.

Although, I have to admit that using Eigen has been a bit of a learning curve, so it's likely I'm making a mistake somewhere.

**Comment by DanielChappuis** [comment] 2021-02-15 10:38
Can you post what are exactly the data returned by the calls to Mesh.Indices.data() and Mesh.Vertices.data() in your code for the single triangle case ? What are the exact values and types of the returned data ?

**Comment by KarateKidzz** [comment] 2021-02-15 11:23
`.data()` returns a templated pointer to the internal Eigen array. So for vertices it returns a `double*` and indices it returns an `int*`.

```
(std::vector<double, std::allocator<double> >) DebugVerts = size=72 {
  [0] = 2.7627117787112079
  [1] = -1.5
  [2] = 1.9019525646456685
  [3] = 0.1360650155101899
  [4] = -1.5
  [5] = 3.3513409617563674
  [6] = 2.7627117787112079
  [7] = 1.5
  [8] = 1.9019525646456685
  [9] = 0.1360650155101899
  [10] = 1.5
  [11] = 3.3513409617563674
  [12] = -0.1360650155101899
  [13] = 1.5
  [14] = -3.3513409617563674
  [15] = -2.7627117787112079
  [16] = 1.5
  [17] = -1.9019525646456685
  [18] = -0.1360650155101899
  [19] = -1.5
  [20] = -3.3513409617563674
  [21] = -2.7627117787112079
  [22] = -1.5
  [23] = -1.9019525646456685
  [24] = 2.7627117787112079
  [25] = 1.5
  [26] = 1.9019525646456685
  [27] = 0.1360650155101899
  [28] = 1.5
  [29] = 3.3513409617563674
  [30] = -0.1360650155101899
  [31] = 1.5
  [32] = -3.3513409617563674
  [33] = -2.7627117787112079
  [34] = 1.5
  [35] = -1.9019525646456685
  [36] = -0.1360650155101899
  [37] = -1.5
  [38] = -3.3513409617563674
  [39] = 2.7627117787112079
  [40] = -1.5
  [41] = 1.9019525646456685
  [42] = 0.1360650155101899
  [43] = -1.5
  [44] = 3.3513409617563674
  [45] = -2.7627117787112079
  [46] = -1.5
  [47] = -1.9019525646456685
  [48] = 0.1360650155101899
  [49] = -1.5
  [50] = 3.3513409617563674
  [51] = 0.1360650155101899
  [52] = 1.5
  [53] = 3.3513409617563674
  [54] = -2.7627117787112079
  [55] = 1.5
  [56] = -1.9019525646456685
  [57] = -2.7627117787112079
  [58] = -1.5
  [59] = -1.9019525646456685
  [60] = -0.1360650155101899
  [61] = -1.5
  [62] = -3.3513409617563674
  [63] = -0.1360650155101899
  [64] = 1.5
  [65] = -3.3513409617563674
  [66] = 2.7627117787112079
  [67] = 1.5
  [68] = 1.9019525646456685
  [69] = 2.7627117787112079
  [70] = -1.5
  [71] = 1.9019525646456685
}
```

```
(std::vector<int, std::allocator<int> >) DebugInds = size=36 {
  [0] = 0
  [1] = 2
  [2] = 3
  [3] = 0
  [4] = 3
  [5] = 1
  [6] = 8
  [7] = 4
  [8] = 5
  [9] = 8
  [10] = 5
  [11] = 9
  [12] = 10
  [13] = 6
  [14] = 7
  [15] = 10
  [16] = 7
  [17] = 11
  [18] = 12
  [19] = 13
  [20] = 14
  [21] = 12
  [22] = 14
  [23] = 15
  [24] = 16
  [25] = 17
  [26] = 18
  [27] = 16
  [28] = 18
  [29] = 19
  [30] = 20
  [31] = 21
  [32] = 22
  [33] = 20
  [34] = 22
  [35] = 23
}
```

For the sake of seeing this data in the IDE, I stuck the Eigen's raw array in a vector:

```
std::vector<double> DebugVerts;
std::vector<int> DebugInds;
        
DebugVerts.assign(Mesh.Vertices.data(), Mesh.Vertices.data() + Mesh.Vertices.size());
DebugInds.assign(Mesh.Indices.data(), Mesh.Indices.data() + Mesh.Indices.size());
```

**Comment by DanielChappuis** [comment] 2021-02-15 17:14
In your code:

> std::unique_ptr<TriangleVertexArray> TriangleArray (new TriangleVertexArray(static_cast<unsigned int>(Mesh.Vertices.cols()),
>                                                                      Mesh.Vertices.data(),
>                                                                      3 * sizeof(double),
>                                                                      **static_cast<unsigned int>(Mesh.Indices.cols())**,
>                                                                      Mesh.Indices.data(),
>                                                                      3 * sizeof(int),
>                                                                      TriangleVertexArray::VertexDataType::VERTEX_DOUBLE_TYPE,
>                                                                      TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE));

The 4th parameter of the TriangleArray constructor must be the number of triangles (as described in the [documentation](https://reactphysics3d.com/usermanual.html#x1-5100011.1.5)). Therefore, in your code you might `need` to replace:

`static_cast<unsigned int>(Mesh.Indices.cols())`

by

`static_cast<unsigned int>(Mesh.Indices.cols()) / 3`

Could you try this change ?

**Comment by KarateKidzz** [comment] 2021-02-15 20:01
I've just tried this with no change in outcome.

I also believe each column defines one face (as one column contains three rows or indices), so `.cols()` should correctly return the number of triangles.

I've done a quick test by creating some temp vertices and indices:
```
const int NumberOfVerts = 3;
        
        double TempVerts[3*NumberOfVerts];
        
        TempVerts[0] = TempVerts[1] = TempVerts[2] = 0.0f;
        
        TempVerts[3] = 0.0f;
        TempVerts[4] = 1.0f;
        TempVerts[5] = 0.0f;
        
        TempVerts[6] = 0.0f;
        TempVerts[7] = 0.0f;
        TempVerts[8] = 1.0f;
        
        const int NumberOfTriangles = 1;
        int TempIndices[NumberOfTriangles * 3];
        
        TempIndices[0] = 0;
        TempIndices[1] = 2;
        TempIndices[2] = 1;
```
and things work, which made me wonder about the difference between `double TempVerts[3*NumberOfVerts];` and `double* data`.

`.data()` returns a pointer to the first element in the array.

I might be asking a stupid C question but is there a difference between passing the array variable, versus passing the pointer to the first element?

**Comment by DanielChappuis** [comment] 2021-02-16 20:39
> I might be asking a stupid C question but is there a difference between passing the array variable, versus passing the pointer to the first element?

Yes that's strange. There should not be any differences.

**Comment by KarateKidzz** [comment] 2021-02-17 10:15
I've done a little more testing and believe that part of the problem is the library reading from `.data()`.

Here's the code I've just tested:

```
const int NumberOfVerts = 3;
double TempVerts[3*NumberOfVerts];
        
        TempVerts[0] = Mesh.Vertices.data()[0];
        TempVerts[1] = Mesh.Vertices.data()[1];
        TempVerts[2] = Mesh.Vertices.data()[2];
        TempVerts[3] = Mesh.Vertices.data()[3];
        TempVerts[4] = Mesh.Vertices.data()[4];
        TempVerts[5] = Mesh.Vertices.data()[5];
        TempVerts[6] = Mesh.Vertices.data()[6];
        TempVerts[7] = Mesh.Vertices.data()[7];
        TempVerts[8] = Mesh.Vertices.data()[8];
        
        const int NumberOfTriangles = 1;
        int TempIndices[NumberOfTriangles * 3];
        
        TempIndices[0] = Mesh.Indices.data()[0];
        TempIndices[1] = Mesh.Indices.data()[1];
        TempIndices[2] = Mesh.Indices.data()[2];
    
        std::unique_ptr<TriangleVertexArray> TriangleArray (new TriangleVertexArray(NumberOfVerts,
                                                                                    TempVerts,
                                                                                    3 * sizeof(double),
                                                                                    NumberOfTriangles,
                                                                                    TempIndices,
                                                                                    3 * sizeof(int),
                                                                                    TriangleVertexArray::VertexDataType::VERTEX_DOUBLE_TYPE,
                                                                                    TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE));
```

This results in a different assertion: `assert(arcSinA >= decimal(0.0));` on line 166 of TriangleVertexArray.cpp.

```
#4	0x000000015fbc8472 in reactphysics3d::TriangleVertexArray::computeVerticesNormals() at OpenPL/External/ReactPhysics3D/src/collision/TriangleVertexArray.cpp:166
#5	0x000000015fbc80bd in reactphysics3d::TriangleVertexArray::TriangleVertexArray(unsigned int, void const*, unsigned int, unsigned int, void const*, unsigned int, reactphysics3d::TriangleVertexArray::VertexDataType, reactphysics3d::TriangleVertexArray::IndexDataType) at OpenPL/External/ReactPhysics3D/src/collision/TriangleVertexArray.cpp:68
#6	0x000000015fbc86cc in reactphysics3d::TriangleVertexArray::TriangleVertexArray(unsigned int, void const*, unsigned int, unsigned int, void const*, unsigned int, reactphysics3d::TriangleVertexArray::VertexDataType, reactphysics3d::TriangleVertexArray::IndexDataType) at OpenPL/External/ReactPhysics3D/src/collision/TriangleVertexArray.cpp:53
#7	0x000000015fc59657 in PL_SCENE::FillVoxels() at OpenPL/Source/Private/Objects/Private/PL_SCENE.cpp:421
```

If we can assume that the geometry data will always cause this assert, it's definitely struggling to read from `.data()`.

Should I move away from using a concave collider? My only real goal is to have a better collider than an AABB or OBB. I'm looking for a "good enough" solution that the user can pass *any* mesh to the library and the physics will be accurate enough to not really notice it's not perfect because I'd rather not have to ask the user what type of collider they'd like for each mesh.

**Comment by DanielChappuis** [comment] 2021-02-17 20:58
I am not sure I understand your test. In your code, you are basically copying the values from data() into two arrays for vertices and indices and then you create a TriangleVertexArray using those arrays. You say that in your test you still have errors ? But in your test, values are not coming from data() but from standard arrays ? Is this also not working ? I thought you said previously that you had errors only when using data() but not when using standard arrays.

**Comment by KarateKidzz** [comment] 2021-02-17 23:01
The test array with test values worked. The test array with values copied from `.data()` returned a new error. And using `.data()` returns the original error.

So the assert from copying is `assert(arcSinA >= decimal(0.0));`.
The assert from using data is `assert(contactPoints[i].size() == 0);`.

I tested this because I was hoping that normal arrays would work. However, it seems the data itself is also incorrect in some way. However, possibly if we could fix the error that results from copying the array, it could work - and we could avoid using `.data()`.

**Comment by KarateKidzz** [comment] 2021-02-18 12:30
I've swapped to a different library. I think this is a nice library, but I'm probably not using it as intended, so causing issues. Thanks for your help during this!

**Comment by liordino** [comment] 2021-07-21 19:49
Hey! Is there any news about this? I had the same idea for a voxelized collision system and I'm getting the same assertion error.

**Comment by DanielChappuis** [comment] 2021-07-22 13:45
Hello. As you can see in the previous discussion, I didn't have enough information to reproduce the issue on my side.

If you have a small code that fails and that I can try on my side, feel free to reopen the issue and post your code.

**Comment by liordino** [comment] 2021-07-22 17:25
Thanks @DanielChappuis !

I'm posting my code here instead of opening another issue so I don't create another one for the same problem, but it seems that I can't reopen it because I'm not a contributor (yet, I hope). Can you do that or should I open another one?

So my issue is the same as @KarateKidzz . Since rp3d don't support concave x concave collision (and correct me if I'm wrong, but it would be very slow for an interactive application anyway), my idea was to "voxelize" the concave meshes recursively by dividing it's aabb until a maximum box size is reached, and them get all of the leafs that collides with the concave mesh itself and add all of them to a rigid body wich will be the effective collision body for this particular mesh. I hope this conveys the gist of it.

The thing is: it seems that every time that a box collides with the mesh the assertion error **assert(contactPoints[i].size() == 0)** is caught. Now comes my first question, before sharing a part of the code which I believe should be reproduce the issue: what exactly is this assertion checking? Because knowing this I may be able to fix it.

Now, time for some code:

The first part is the code which subdivides an aabb into octants. It receives an stop condition so it knows when to stop subdividing the voxels:

```
typedef struct octree_t_
{
private:
void build_tree(std::function<bool(extent3)> stop_condition)
{
	if (stop_condition(extents))
		return;

	point3 center = extents.center();

	//Create subdivided regions for each octant
	extent3 octants[8];
	octants[0] = extent3(extents.pmin, center);
	octants[1] = extent3(point3(center.x, extents.pmin.y, extents.pmin.z), point3(extents.pmax.x, center.y, center.z));
	octants[2] = extent3(point3(center.x, extents.pmin.y, center.z), point3(extents.pmax.x, center.y, extents.pmax.z));
	octants[3] = extent3(point3(extents.pmin.x, extents.pmin.y, center.z), point3(center.x, center.y, extents.pmax.z));
	octants[4] = extent3(point3(extents.pmin.x, center.y, extents.pmin.z), point3(center.x, extents.pmax.y, center.z));
	octants[5] = extent3(point3(center.x, center.y, extents.pmin.z), point3(extents.pmax.x, extents.pmax.y, center.z));
	octants[6] = extent3(center, extents.pmax);
	octants[7] = extent3(point3(extents.pmin.x, center.y, center.z), point3(center.x, extents.pmax.y, extents.pmax.z));

	for (int i = 0; i < 8; i++)
		child_nodes.push_back(octree(octants[i], stop_condition));
}

public:
extent3 extents;
varray<octree_t_> child_nodes;

octree_t_() { }

octree_t_(extent3 e, std::function<bool(extent3)> stop_condition) : extents(e)
{
	build_tree(stop_condition);
}
} octree;
```
And here's the code which uses it. This one grabs a mesh, creates it's rigid body as a concave one, and after that get's the aabb from it and subdivide it until any of it's dimensions is lower than 6 units or it don't collide with the concave body. In the case that a box with any dimension lower than 6 and which collides with the body is found, it's added to the voxelized mesh rigid body:
```
// First get all the points, normals and indices from the mesh (make sure that we're getting the right data)
auto allPoints = model->points->vertices();
auto nbPoints = allPoints.size();

std::vector<float> points;
std::vector<float> normals;

points.reserve(nbPoints);
normals.reserve(nbPoints);

for (auto vertex : allPoints)
{
    point3 point = vertex->pos;
    point3 normal = point3::unpack_S128(vertex->norm);

    points.push_back(point.x);
    points.push_back(point.y);
    points.push_back(point.z);

    normals.push_back(normal.x);
    normals.push_back(normal.y);
    normals.push_back(normal.z);
}

auto allFaces = model->allFaces();
auto nbFaces = (size_t)allFaces.size();

std::vector<int> indices;

indices.reserve(nbFaces * 3);

for (auto face : allFaces)
{
    indices.push_back(face->a);
    indices.push_back(face->b);
    indices.push_back(face->c);
}

// Create the concave mesh shape and it's rigid body
rp3d::TriangleVertexArray* triangleArray =
    new rp3d::TriangleVertexArray(
        nbPoints, points.data(), sizeof(float) * 3,
        normals.data(), sizeof(float) * 3,
        nbFaces, indices.data(), sizeof(int) * 3,
        rp3d::TriangleVertexArray::VertexDataType::VERTEX_FLOAT_TYPE,
        rp3d::TriangleVertexArray::NormalDataType::NORMAL_FLOAT_TYPE,
        rp3d::TriangleVertexArray::IndexDataType::INDEX_INTEGER_TYPE);

rp3d::TriangleMesh* triangleMesh = sce->physics_common.createTriangleMesh();
triangleMesh->addSubpart(triangleArray);

rp3d::ConcaveMeshShape* concaveMesh = sce->physics_common.createConcaveMeshShape(triangleMesh);

rp3d::RigidBody* concaveMeshBody = sce->physics_world->createRigidBody(rp3d::Transform::identity());
concaveMeshBody->addCollider(concaveMesh, rp3d::Transform::identity());

// Create and fill the mesh "voxelized" rigid body, wich will consist of several boxes that simplifies it's geometry
rp3d::RigidBody* rigidBody = sce->physics_world->createRigidBody(rp3d::Transform::identity());

float MIN_DIMENSION = 6;
octree octree = {
    { aabb },
    { [this, sce, concaveMeshBody, rigidBody, MIN_DIMENSION](extent3 e)
        {
            point3 dimensions = e.dimensions();
            bool should_stop = dimensions.x <= MIN_DIMENSION && dimensions.y <= MIN_DIMENSION && dimensions.z <= MIN_DIMENSION;

            // If box still didn't reached the minimum dimension, keep subdividing
            if (!should_stop)
                return false;

            // Create rigid body for current box and test if it collides with the concave mesh body
            rp3d::RigidBody* boxBody = sce->physics_world->createRigidBody(rp3d::Transform::identity());
            rp3d::Vector3 boxPosition(e.pmin.x, e.pmin.y, e.pmin.z);
            rp3d::Transform boxTransform(boxPosition, rp3d::Quaternion::identity());
            rp3d::Vector3 half_dimensions(dimensions.x / 2, dimensions.y / 2, dimensions.z / 2);
            rp3d::BoxShape* boxShape = sce->physics_common.createBoxShape(half_dimensions);
            boxBody->addCollider(boxShape, boxTransform);

            // Only add this box if if collides with the concave mesh
            if (sce->physics_world->testOverlap(concaveMeshBody, boxBody))
                rigidBody->addCollider(boxShape, boxTransform); // This line is never reached because everytime that a collision is found the assertion error occurs

            return true;
        }
    }
};

// After that the item's voxelized rigid body should be ready
```
I never get to the **rigidBody->addCollider(boxShape, boxTransform)** instruction, though, because every time that a collision is found the assertion error is caught. Also, here's an example content data from [points.data()](https://pastebin.com/yEjhevkE), [normals.data()](https://pastebin.com/7Db6qdi2) and [indices.data()](https://pastebin.com/4SA9Pxs7). And here's the AABB data from this particular example:

Min: (-12.9984999, 0.00000000, -0.500000000)
Max: (12.9984999, 36.0000000, 0.500000000)

I'm still debugging it here, so if I find something else I'll update it.
Let me know if I can provide something else.

Thanks again!

**Comment by KarateKidzz** [comment] 2021-07-22 17:38
@liordino Just reopened for you. Feel free to open a separate issue though if that becomes easier

**Comment by liordino** [comment] 2021-07-22 17:42
Thanks @KarateKidzz !

And I have some news already: I'm not sure if that's the cause of the issue, but while debugging it to share the code I printed an obj file for this mesh that I used as an example here and that's what I got on meshlab:

![image](https://user-images.githubusercontent.com/607600/126684292-a20625e4-05ab-4d3d-b7cf-ff3725c9cc8a.png)

The cause  is that this one is made of some fragments but I'm treating it as a single entity. I'll create the separate meshes and get back asap with the results.

**Comment by liordino** [comment] 2021-07-22 22:06
Hey, I just managed to fix the mesh, which's made of two subparts (I changed the code a bit) but am still getting the same assertion error. Here are the objs for the [first](https://pastebin.com/gLJ46QDg) and the [second](https://pastebin.com/PQvvV4sG), so we can try to find out why is that. Thanks again!

**Comment by DanielChappuis** [comment] 2021-07-23 06:50
> @liordino Just reopened for you. Feel free to open a separate issue though if that becomes easier

Thanks @KarateKidzz 

> The thing is: it seems that every time that a box collides with the mesh the assertion error **assert(contactPoints[i].size() == 0)** is caught. Now comes my first question, before sharing a part of the code which I believe should be reproduce the issue: what exactly is this assertion checking? Because knowing this I may be able to fix it.

What would help a lot is the complete stack trace when the break point is hit. At least, I need to know in which file and which line is this break point but the stack trace would be better. Could you post a stack trace?

**Comment by liordino** [comment] 2021-07-23 12:47
> What would help a lot is the complete stack trace when the assert is hit. At least, I need to know in which file and which line is this assert but the stack trace would be better. This way, I will be able to tell you what is the goal of this assert. Could you post a stack trace?

Sure! The assertion is on line 133 of the NarrowPhaseInfoBatch.cpp file, on the void NarrowPhaseInfoBatch::clearmethod, and here goes the stack trace:

>	rdx11_x64_d.dll!reactphysics3d::NarrowPhaseInfoBatch::clear() Line 133	C++
 	rdx11_x64_d.dll!reactphysics3d::NarrowPhaseInfoBatch::~NarrowPhaseInfoBatch() Line 47	C++
 	[External Code]	
 	rdx11_x64_d.dll!reactphysics3d::CollisionDetectionSystem::testOverlap(reactphysics3d::CollisionBody * body1, reactphysics3d::CollisionBody * body2) Line 1491	C++
 	rdx11_x64_d.dll!reactphysics3d::PhysicsWorld::testOverlap(reactphysics3d::CollisionBody * body1, reactphysics3d::CollisionBody * body2) Line 304	C++
 	rdx11_x64_d.dll!scene::item::try_prepare::__l65::<lambda>(base::extent3_t_ e) Line 1814	C++
 	[External Code]	
 	rdx11_x64_d.dll!base::octree_t_::build_tree(std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 818	C++
 	rdx11_x64_d.dll!base::octree_t_::octree_t_(base::extent3_t_ e, std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 853	C++
 	rdx11_x64_d.dll!base::octree_t_::build_tree(std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 836	C++
 	rdx11_x64_d.dll!base::octree_t_::octree_t_(base::extent3_t_ e, std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 853	C++
 	rdx11_x64_d.dll!base::octree_t_::build_tree(std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 836	C++
 	rdx11_x64_d.dll!base::octree_t_::octree_t_(base::extent3_t_ e, std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 853	C++
 	rdx11_x64_d.dll!base::octree_t_::build_tree(std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 836	C++
 	rdx11_x64_d.dll!base::octree_t_::octree_t_(base::extent3_t_ e, std::function<bool __cdecl(base::extent3_t_)> stop_condition) Line 853	C++
 	rdx11_x64_d.dll!scene::item::try_prepare(scene::IResourceStore * ploader, scene::group_scene * sce) Line 1791	C++
 	rdx11_x64_d.dll!scene::group_scene::_for_render(const base::ray3 & los, std::vector<std::shared_ptr<scene::item>,std::allocator<std::shared_ptr<scene::item> > > & o, bool modelOrBox) Line 3116	C++
 	rdx11_x64_d.dll!scene::group_scene::visible_items(const base::ray3 & Los, bool modelOrBox) Line 750	C++
 	rdx11_x64_d.dll!rendering::render_list::prepare(const base::ray3 & Los, std::function<bool __cdecl(scene::item const *)> IFilt, const scene::IMaterial * overrideMtl, bool * needs_update) Line 741	C++
 	rdx11_x64_d.dll!rendering::scene_renderer::RenderExternalScene(std::shared_ptr<scene::group_scene> scene, std::shared_ptr<scene::IViewpoint> eye, rendering::RenderMode mode, bool * needs_update) Line 170	C++
 	rdx11_x64_d.dll!rendering::dx11::Renderer::Render(rendering::RenderMode mode, bool force) Line 464	C++
 	rdx11_x64_d.dll!windows::RendererFactory::Rerender(HWND__ * w) Line 255	C++
 	rdx11_x64_d.dll!RC_ClassWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 282	C++
 	[External Code]	
 	rdx11_x64_d.dll!windows::ui_tracker::ProcessWindowsMessage(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 744	C++
 	rdx11_x64_d.dll!windows::_Ui_Tracker_Func(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 420	C++
 	[External Code]	

Thanks!

**Comment by liordino** [comment] 2021-07-28 20:09
Hey @DanielChappuis ! I just tested it and there's no more assertion errors. I'll add some code to show the voxels on the UI so I can make sure that I'm getting the right ones, but I guess the issue is fixed. Thank you!

**Comment by DanielChappuis** [comment] 2021-07-29 19:29
@liordino Thanks a lot for your feedback. I have merged the fix into the [master](https://github.com/DanielChappuis/reactphysics3d/tree/master) branch.

I am closing this issue.

**Closed by DanielChappuis** 2021-07-29 19:29 UTC
