### ISSUE TITLE
Wrong scaling in ConcaveMeshShape

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#50] opened 2018-05-24 03:10 UTC
Hi,

scaling seems to be wrong in ConcaveMeshShape. Please see attached a patch:

```
diff --git a/ext/reactphysics3d/src/collision/shapes/ConcaveMeshShape.cpp b/ext/reactphysics3d/src/collision/shapes/ConcaveMeshShape.cpp
index 79c431e0..4864e56d 100644
--- a/ext/reactphysics3d/src/collision/shapes/ConcaveMeshShape.cpp
+++ b/ext/reactphysics3d/src/collision/shapes/ConcaveMeshShape.cpp
@@ -64,9 +64,15 @@ void ConcaveMeshShape::initBVHTree() {
             triangleVertexArray->getTriangleVertices(triangleIndex, trianglePoints);
 
             // Apply the scaling factor to the vertices
-            trianglePoints[0] *= mScaling.x;
-            trianglePoints[1] *= mScaling.y;
-            trianglePoints[2] *= mScaling.z;
+            trianglePoints[0][0] *= mScaling.x;
+            trianglePoints[0][1] *= mScaling.y;
+            trianglePoints[0][2] *= mScaling.z;
+            trianglePoints[1][0] *= mScaling.x;
+            trianglePoints[1][1] *= mScaling.y;
+            trianglePoints[1][2] *= mScaling.z;
+            trianglePoints[2][0] *= mScaling.x;
+            trianglePoints[2][1] *= mScaling.y;
+            trianglePoints[2][2] *= mScaling.z;
 
             // Create the AABB for the triangle
             AABB aabb = AABB::createAABBForTriangle(trianglePoints);
@@ -88,9 +94,15 @@ void ConcaveMeshShape::getTriangleVertices(uint subPart, uint triangleIndex,
     triangleVertexArray->getTriangleVertices(triangleIndex, outTriangleVertices);
 
     // Apply the scaling factor to the vertices
-    outTriangleVertices[0] *= mScaling.x;
-    outTriangleVertices[1] *= mScaling.y;
-    outTriangleVertices[2] *= mScaling.z;
+    outTriangleVertices[0][0] *= mScaling.x;
+    outTriangleVertices[0][1] *= mScaling.y;
+    outTriangleVertices[0][2] *= mScaling.z;
+    outTriangleVertices[1][0] *= mScaling.x;
+    outTriangleVertices[1][1] *= mScaling.y;
+    outTriangleVertices[1][2] *= mScaling.z;
+    outTriangleVertices[2][0] *= mScaling.x;
+    outTriangleVertices[2][1] *= mScaling.y;
+    outTriangleVertices[2][2] *= mScaling.z;
 }
 
 // Return the three vertex normals (in the array outVerticesNormals) of a triangle
```
Best regards
Andreas

**Comment by DanielChappuis** [comment] 2018-05-24 07:27
Thanks a lot for reporting this.  The issue is now fixed in the master branch.

**Closed by DanielChappuis** 2018-05-24 07:27 UTC
Labels: bug
