### ISSUE TITLE
assert(std::abs(determinant) > MACHINE_EPSILON)

### ISSUE THREAD

**Issue by ghost** [DanielChappuis/reactphysics3d#138] opened 2020-04-18 09:42 UTC
Hey,

I'm innocently using ReactPhysics3D and am getting this assert raised... and not sure how to go around debugging it.

Ian

**Comment by Omroth** [comment] 2020-04-18 09:45
![image](https://user-images.githubusercontent.com/48519294/79634317-a481c400-8161-11ea-9640-5ad036142211.png)

This is the stack trace if it helps.

**Comment by DanielChappuis** [comment] 2020-08-25 10:15
Sorry, I think I missed this issue.

Do you still having some issues ? Can you share some code so that I can try to reproduce this issue ?

**Comment by franciscotv** [comment] 2020-09-29 02:45
> Hey,
> 
> I'm innocently using ReactPhysics3D and am getting this assert raised... and not sure how to go around debugging it.
> 
> Ian

Hi there, in my opinion, that assertion just means that the determinant is zero (or too small), hence the matrix you calculated its determinant, is not invertible, which means that does not have a solution because one of the rows can be eliminated by substitution of another row in the matrix, i.e. some of the rows in the matrix is a linear combination of some other, they are not linearly dependent.

**Comment by DanielChappuis** [comment] 2024-02-13 22:57
I am closing this issue. Feel free to reopen it if you have a code example that is failing with this error.

**Closed by DanielChappuis** 2024-02-13 22:57 UTC
