### ISSUE TITLE
addCollisionShape() fails assert in debug build

### ISSUE THREAD

**Issue by ColinGilbert** [DanielChappuis/reactphysics3d#22] opened 2015-08-29 05:38 UTC
Using GCC 4.9.3 (on Gentoo.) Both master and develop branches exhibit this behaviour. Works fine for release builds.

```
/home/noob/noobgame/engine/lib/reactphysics3d/src/body/RigidBody.cpp:216: virtual reactphysics3d::ProxyShape* reactphysics3d::RigidBody::addCollisionShape(const reactphysics3d::CollisionShape&, const reactphysics3d::Transform&, reactphysics3d::decimal): Assertion `mass > decimal(0.0)' failed.
```

Please ask if you need more info.

**Comment by DanielChappuis** [comment] 2015-08-31 05:49
Thanks for reporting this.

Can I ask you to post the code where you create the CollisionShape that you are trying to add to the body ?

**Comment by ColinGilbert** [comment] 2015-09-02 19:06
I was trying to add a convex hull. Worked around by changing the default mass to 1.0

```
void noob::prop::attach_hull(const noob::basic_mesh& hull, float mass, const noob::vec3& position, const noob::versor& orientation)
{
		rp3d::ConvexMeshShape shape(&hull.vertices[0].v[0], hull.vertices.size(), 3 * sizeof(float));
		
		for (size_t i = 0; i < hull.indices.size(); i += 3)
		{
			float first = hull.indices[i];
			float second = hull.indices[i+1];
			float third = hull.indices[i+2];

			shape.addEdge(first, second);
			shape.addEdge(first, third);
			shape.addEdge(second, third);
		}
		
		shape.setIsEdgesInformationUsed(true);
		
		body->addCollisionShape(shape, rp3d::Transform(rp3d::Vector3(position.v[0], position.v[1], position.v[2]), rp3d::Quaternion(orientation.q[0], orientation.q[1], orientation.q[2], orientation.q[3])), mass);
}
```

**Comment by DanielChappuis** [comment] 2015-09-03 05:49
When it failed, what value were you using for the "mass" in the addCollisionShape() call ? The mass has to be a positive value.

**Comment by ColinGilbert** [comment] 2015-09-03 06:36
1.0

**Comment by DanielChappuis** [comment] 2015-09-03 09:36
I'm not sure I understand. You mean it fails if you use 1.0 for the mass ? Then, you said it worked if you changed the mass to 1.0.

**Comment by ColinGilbert** [comment] 2015-09-03 17:59
Oh sorry, I miswrote. What I meant was that the default mass was 0.0. Oops!

**Comment by DanielChappuis** [comment] 2015-09-03 20:10
Ok so if I understand correctly, I can close this issue because this is not a bug right ? There is no default value for the mass in the addCollisionShape() method and the user has to use a positive value for the mass in parameter. Am I missing something ?

**Closed** 2015-09-08 07:11 UTC
