### ISSUE TITLE
Question about  solvePositionCorrection 

### ISSUE THREAD

**Issue by liuqiangNetease** [DanielChappuis/reactphysics3d#73] opened 2018-10-03 16:18 UTC
hello,   when I test HingeJoint,  there are two shapes in the righidbody,  and the rigid body  connect a static rigid body.     the dynamic rigid body rotate around z axis,  and anchor point is(-1, 0, 0).   it works
but the dynamic rigid body's position is wrong,  I expect the position is (0,0,0) in original.  but the position is (0.5,0,0).  it is not the same as the Position in Unity3d.   
So, I do things like below:
      rp3d::WorldSettings settings;  settings.defaultPositionSolverNbIterations = 0;
the original(or Init) position is right, but the anchor point has some offset, not I respected.

All in all , when I export unity physics data, and import the data to my app.  the hingeJoint simulate result is not right.

**Comment by DanielChappuis** [comment] 2018-10-03 16:45
Can you post the code that you use to create the bodies and the joint ? I am not sure I really understand your configuration. Then, explain what you expect and what you observe precisely.

**Comment by liuqiangNetease** [comment] 2018-10-05 02:58
//create static rigid body
rp3d::Transform t(rp3d::Vector3(0,0,0), rp3d::Quaternion::identity);
rp3d::RigidBody* mStaticBody = m_pWorld->createRigidBody(t);
mStaticBody->setType(rp3d::BodyType::STATIC);

//create dynamic rigid body, initial position is Vector3(0,0,0)
rp3d::RigidBody* mDynBody = m_pWorld->createRigidBody(t);
mDynBody->setType(rp3d::BodyType::DYNAMIC);
mDynBody->enableGravity(true);
//add shapes for dynamic rigid body
rp3d::Vector3 halfExtend(0.25,0.25, 0.25);
rp3d::BoxShape* pShape = new rp3d::BoxShape(halfExtend);
rp3d::Transform relative(rp3d::Vector3(0,0,0), rp3d::Quaternion::identity);
rp3d::ProxyShape* proxyShape = mDynBody->addCollisionShape(pShape, relative, rp3d::decimal(0.5f));

halfExtend = rp3d::Vector3(0.1, 0.1, 0.1);
rp3d::BoxShape* pShape2 = new rp3d::BoxShape(halfExtend);
rp3d::Transform relative2(rp3d::Vector3(-1,0,0), rp3d::Quaternion::identity);
rp3d::ProxyShape* proxyShape2 = mDynBody->addCollisionShape(pShape2, relative2, rp3d::decimal(0.5f));

//create HingeJoint
rp3d::HingeJointInfo jointInfo(mStaticBody, mDynBody, rp3d::Vector3(-1,0,0), rp3d::Vector3(0,0,1));
m_pWorld->createJoint(jointInfo);

The dynamic Rigidbody's Initial Position is wrong.  when use mDynBody->getTransform() to debug, the position is Vector3(0.5,0, 0) , and I expect Vector3(0,0,0)

**Comment by liuqiangNetease** [comment] 2018-10-05 10:05
Sorry, it is my fault.    thank u for reply.

**Comment by DanielChappuis** [comment] 2018-10-05 12:12
Oh ok did you solve your problem ? I mean is it working as expected now ?

**Comment by liuqiangNetease** [comment] 2018-10-06 05:49
New Case I donot understand. the code as below:
//create static rigid body
rp3d::Transform t(rp3d::Vector3(0,0,0), rp3d::Quaternion::identity);
rp3d::RigidBody* mStaticBody = m_pWorld->createRigidBody(t);
mStaticBody->setType(rp3d::BodyType::STATIC);

//create dynamic rigid body, initial position is Vector3(0,0,0), init Orientation is Quaternion(0,0,0,1)
rp3d::RigidBody* mDynBody = m_pWorld->createRigidBody(t);
mDynBody->setType(rp3d::BodyType::DYNAMIC);
mDynBody->enableGravity(true);
//add shapes for dynamic rigid body
rp3d::Vector3 halfExtend(0.5,0.5, 0.5);
rp3d::BoxShape* pShape = new rp3d::BoxShape(halfExtend);
rp3d::Transform relative(rp3d::Vector3(1,0,0), rp3d::Quaternion::identity);
rp3d::ProxyShape* proxyShape = mDynBody->addCollisionShape(pShape, relative, rp3d::decimal(50));

halfExtend = rp3d::Vector3(0.5, 0.5, 0.5);
rp3d::BoxShape* pShape2 = new rp3d::BoxShape(halfExtend);
rp3d::Transform relative2(rp3d::Vector3(0,-1,0), rp3d::Quaternion::identity);
rp3d::ProxyShape* proxyShape2 = mDynBody->addCollisionShape(pShape2, relative2, rp3d::decimal(50));

//create HingeJoint
rp3d::HingeJointInfo jointInfo(mStaticBody, mDynBody, rp3d::Vector3(-1,0,0), rp3d::Vector3(0,0,1));
m_pWorld->createJoint(jointInfo);

The dynamic Rigidbody's Initial Position is wrong. when use mDynBody->getTransform() to debug, the position is Vector3(-0.37548,0.33162, 0) , and Orientation is Quaternion(0,0,-0.148, 0.9889) and I expect dynamic rigid body init position Vector3(0,0,0), init Orientation Quaternion(0,0,0,1)

I cannot understand why in the hingeJoint ,the dynamic rigid body's Transform has changed. 
so I simulation is not right at all.

**Comment by DanielChappuis** [comment] 2018-10-06 06:50
Can you tell me after which line in your code the position of the dynamic rigid body has changed for the first time ? I mean, which call exactly in your code changes the position ?

**Comment by liuqiangNetease** [comment] 2018-10-06 13:18
I delete any of a shape, and it also not right, the code as below:
//create static rigid body
rp3d::Transform t(rp3d::Vector3(0,0,0), rp3d::Quaternion::identity);
rp3d::RigidBody* mStaticBody = m_pWorld->createRigidBody(t);
mStaticBody->setType(rp3d::BodyType::STATIC);

//create dynamic rigid body, initial position is Vector3(0,0,0), init Orientation is Quaternion(0,0,0,1)
rp3d::RigidBody* mDynBody = m_pWorld->createRigidBody(t);
mDynBody->setType(rp3d::BodyType::DYNAMIC);
mDynBody->enableGravity(true);
//add shapes for dynamic rigid body
rp3d::Vector3 halfExtend(0.5,0.5, 0.5);
rp3d::BoxShape* pShape = new rp3d::BoxShape(halfExtend);
rp3d::Transform relative(rp3d::Vector3(1,0,0), rp3d::Quaternion::identity);
rp3d::ProxyShape* proxyShape = mDynBody->addCollisionShape(pShape, relative, rp3d::decimal(50));

//halfExtend = rp3d::Vector3(0.5, 0.5, 0.5);
//rp3d::BoxShape* pShape2 = new rp3d::BoxShape(halfExtend);
//rp3d::Transform relative2(rp3d::Vector3(0,-1,0), rp3d::Quaternion::identity);
//rp3d::ProxyShape* proxyShape2 = mDynBody->addCollisionShape(pShape2, relative2, //rp3d::decimal(50));

//create HingeJoint
rp3d::HingeJointInfo jointInfo(mStaticBody, mDynBody, rp3d::Vector3(-1,0,0), rp3d::Vector3(0,0,1));
m_pWorld->createJoint(jointInfo);

The result is not right too.  the hingeJoint I test three days. and it has some bugs? can you debug it?

**Comment by liuqiangNetease** [comment] 2018-10-08 03:18
when shapes has Offset from body. the simulation may have some problem?  
and in the testbed demos, shape has no offset form rigidbody.

**Comment by DanielChappuis** [comment] 2018-10-18 05:29
I have reproduced you code in my testbed application and I can't observe something that is wrong. You create a dynamic body with a zero position transform. Then you add a box1 collision shape to this body at relative position (-1, 0, 0) and a box2 collision shape at relative position (1, 0, 0). You also create a static body at zero position. Then you create a hinge joint between the two bodies with anchor at position (-1, 0, 0) which is the center of the box1 shape and z-axis direction. When the simulation starts the dynamic rigid body with the two shapes starts to rotate around the z-axis as expected. It is expected that the position of the dynamic body changes because only the point of the body at the center of the box1 won't move (because of the hinge anchor at this position).

When defaultPositionSolverNbIterations = 5, the position of the ProxyShape of the box1 (at the anchor point) stays very close to its initial position (-1, 0, 0). When defaultPositionSolverNbIterations = 0, the position of the ProxyShape of box1 also remains close to (-1, 0, 0) but with a larger difference which is also expected. Same result on my side if I remove the box2.

The velocity solver of the physics engine is not able to make sure that the anchor point of two bodies linked by a joint remains exactly at the same position. That's why we have a position solver that is there to correct the position error. The larger the number of iterations of the position solver (defaultPositionSolverNbIterations in your code) the smaller the position error at the anchor point. If you set defaultPositionSolverNbIterations = 0, you are basically disabling the position correction solver and you might end up with a quite large position error.

Do you only have issues when you set defaultPositionSolverNbIterations = 0 ? Can I ask you why you are setting this value to zero ?

**Comment by liuqiangNetease** [comment] 2018-11-06 03:31
In my view, defaultPositionSolverNbIterations = 0 or defaultPositionSolverNbIterations = 5 ,  I can not get the right simulation.   my simulation result is difference with yours.

**Comment by DanielChappuis** [comment] 2018-11-07 07:34
> I have reproduced you code in my testbed application and I can't observe something that is wrong. You create a dynamic body with a zero position transform. Then you add a box1 collision shape to this body at relative position (-1, 0, 0) and a box2 collision shape at relative position (1, 0, 0). You also create a static body at zero position. Then you create a hinge joint between the two bodies with anchor at position (-1, 0, 0) which is the center of the box1 shape and z-axis direction. When the simulation starts the dynamic rigid body with the two shapes starts to rotate around the z-axis as expected. It is expected that the position of the dynamic body changes because only the point of the body at the center of the box1 won't move (because of the hinge anchor at this position).
>

**Comment by DanielChappuis** [comment] 2018-11-07 07:48
You say with defaultPositionSolverNbIterations = 5 that:

> I can not get the right simulation. my simulation result is difference with yours.
>

But can you describe exactly what you observe in your simulation ? What is different from my description below:

> I have reproduced you code in my testbed application and I can't observe something that is wrong. You create a dynamic body with a zero position transform. Then you add a box1 collision shape to this body at relative position (-1, 0, 0) and a box2 collision shape at relative position (1, 0, 0). You also create a static body at zero position. Then you create a hinge joint between the two bodies with anchor at position (-1, 0, 0) which is the center of the box1 shape and z-axis direction. When the simulation starts the dynamic rigid body with the two shapes starts to rotate around the z-axis as expected. It is expected that the position of the dynamic body changes because only the point of the body at the center of the box1 won't move (because of the hinge anchor at this position). 
>
>When defaultPositionSolverNbIterations = 5, the position of the ProxyShape of the box1 (at the anchor point) stays very close to its initial position (-1, 0, 0). When defaultPositionSolverNbIterations = 0, the position of the ProxyShape of box1 also remains close to (-1, 0, 0) but with a larger difference which is also expected. Same result on my side if I remove the box2.
> 

Can you create a video of your simulation ?

**Comment by DanielChappuis** [comment] 2020-06-02 08:47
I am closing this issue now. Do not hesitate to reopen it if needed.

**Closed by DanielChappuis** 2020-06-02 08:47 UTC
