### ISSUE TITLE
Assert in DynamicAABBTree.h

### ISSUE THREAD

**Issue by andreasdr** [DanielChappuis/reactphysics3d#57] opened 2018-05-30 23:52 UTC
Hi,

i have a new assert which popped up today.
- Assertion failed: (mNodes[nodeID].isLeaf()), function getNodeDataPointer, file ext/reactphysics3d/src/collision/broadphase/DynamicAABBTree.h, line 285.

I guess it happens after adding/removing a body.

The full backtrace looks like:
```
(gdb) bt
#0  0x000000080274384a in thr_kill () from /lib/libc.so.7
#1  0x0000000802743814 in raise () from /lib/libc.so.7
#2  0x0000000802743789 in abort () from /lib/libc.so.7
#3  0x00000008027bee61 in __assert () from /lib/libc.so.7
#4  0x0000000000aa69b3 in reactphysics3d::DynamicAABBTree::getNodeDataPointer (this=0x8062ba5b8, nodeID=1141) at DynamicAABBTree.h:285
#5  0x0000000000aa5e7f in reactphysics3d::BroadPhaseAlgorithm::computeOverlappingPairs (this=0x8062ba5b8, memoryManager=@0x8062ba008)
    at ext/reactphysics3d/src/collision/broadphase/BroadPhaseAlgorithm.cpp:285
#6  0x0000000000ac2afa in reactphysics3d::CollisionDetection::computeBroadPhase (this=0x8062ba4b0) at ext/reactphysics3d/src/collision/CollisionDetection.cpp:100
#7  0x0000000000ac2a99 in reactphysics3d::CollisionDetection::computeCollisionDetection (this=0x8062ba4b0) at ext/reactphysics3d/src/collision/CollisionDetection.cpp:77
#8  0x0000000000acf2c6 in reactphysics3d::DynamicsWorld::update (this=0x8062ba000, timeStep=0.0329999998) at ext/reactphysics3d/src/engine/DynamicsWorld.cpp:126
#9  0x00000000005cb043 in tdme::engine::physics::World::update (this=0x8062ba000, deltaTime=0.0329999998) at src/tdme/engine/physics/World.cpp:179
#10 0x0000000000447729 in asw::ASWServerGameLogicThread::run (this=0x80651d070) at src/asw/ASWServerGameLogicThread.cpp:436
#11 0x0000000000831a94 in tdme::os::threading::Thread::pThreadRun (thread=0x80651d070) at src/tdme/os/threading/Thread.cpp:55
#12 0x000000080245abc5 in pthread_create () from /lib/libthr.so.3
#13 0x0000000000000000 in ?? ()

```
However if disabling assertions everything works as expected.

Best regards
Andreas

**Comment by DanielChappuis** [comment] 2018-06-03 09:54
Thanks for reporting this. 

I am not able to reproduce this. Do you have some code that I can run with this issue ?

**Comment by andreasdr** [comment] 2018-06-03 09:56
Hi,

Will try to set some code up. It will take some time though.

Best regards
Andreas

**Comment by andreasdr** [comment] 2018-07-30 01:12
Hi,

is it possible that this dissappeared with fix of https://github.com/DanielChappuis/reactphysics3d/issues/60 or another one? I was not able to reproduce it today.

Many thanx and 

Best regards
Andreas

**Comment by DanielChappuis** [comment] 2018-07-30 05:14
Hi,

Yes, it might be related. Do you have a test where this bug can be reproduced in your code so that I can check if it has been fixed by the patch for bug #60 ?

**Comment by andreasdr** [comment] 2018-07-30 05:32
Hi,

did not come up with a test until now. Wanted to create one today after #60 has been fixed.
Tested with our game. It disappeared. :)

So I guess its gone.

Many thanx and

Best regards
Andreas

**Comment by DanielChappuis** [comment] 2018-07-30 12:09
Ok thanks. I am closing this issue.

**Closed by DanielChappuis** 2018-07-30 12:09 UTC
